
- hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create static content directory
      file:
        path: /home/{{ ansible_user }}/static
        state: directory
        mode: '0755'

    - name: Copy static content
      copy:
        src: static/
        dest: /home/{{ ansible_user }}/static
        mode: '0644'

    - name: Copy docker-compose file
      copy:
        src: docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-compose.yml
        mode: '0644'

    - name: Start containers
      command: docker compose up -d
      args:
        chdir: /home/{{ ansible_user }}